# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints
#
# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options

include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - only_throw_errors
    - comment_references
    - library_annotations
    - combinators_ordering
    - always_declare_return_types
    - one_member_abstracts
    - cancel_subscriptions
    - avoid_unused_constructor_parameters
    - public_member_api_docs
    - prefer_relative_imports
    - avoid_dynamic_calls
    - cast_nullable_to_non_nullable
    - unnecessary_null_checks
    - tighten_type_of_initializing_formals
    - noop_primitive_operations
    - throw_in_finally
    - prefer_const_constructors_in_immutables

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
