name: hashlib_codecs
description: Fast and error resilient codecs.
homepage: https://github.com/bitanon/hashlib_codecs
version: 1.0.0

environment:
  sdk: ">=2.14.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.4

funding:
  - https://paypal.me/sd1pu
