name: hashlib_codecs
description: Fast and error resilient codecs. Currently supporting Binary(Base2), Hexadecimal(Base16), Base32, Base64, BigInt.
homepage: https://github.com/bitanon/hashlib_codecs
version: 2.0.0

environment:
  sdk: ">=2.14.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.4
  benchmark_harness: ^2.2.1
  base_codecs: ^1.0.1

funding:
  - https://paypal.me/sd1pu
