name: convertlib
description: Fast and error resilient codecs. Supports Base2, Base8, Base16,
  Base32, Base64, BigInt, UTF-8, and the PHC/crypt string format.
homepage: https://github.com/bitanon/convertlib
version: 3.5.2

topics:
  - codec
  - encoding
  - base64
  - base32
  - hex

environment:
  sdk: ">=2.19.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  lints: any
  test: any
  base_codecs: any
  base32: any

funding:
  - https://paypal.me/bitan0n
